### ISSUE TITLE
Issue: Program injected wrong token to X-CSRF-TOKEN header

### ISSUE THREAD

**Issue by Circu1tI0N3rd** [PythonTryHard/BKSchedule_Rewrite#1]
**Describe the bug**
Program reused the form lt value as the token for retrieving the schedule while the schedule requires a different token.

**Steps to reproduce the behavior**
1. Run Wireshark with browser SSL key included for traffic decryption.
2. Navigate to HTTP request "GET /stinfo/lichhoc HTTP/1.1"
3. Compare the value of X-CSRF-TOKEN header against the previously retrieved 'lt' value.

**Expected behavior VS Actual result**
A matching value between the 'lt' input and X-CSRF-TOKEN header VS **_a completely different value_**

**Screenshots**
_[ Censored ]_

**Additional context**
 - Should replace BeautifulSoup4 with other alternatives (BS4 was obsolete as from Python 3.3 + incompatiblity between certain Python-running OSes).
 - Apparently you should do more research in Wireshark as there are always optimal solutions for detecting valid credential (_HTTP 302 Found_ for example).
 - `whoami` : the only guy that dig this far.

**Comment by Circu1tI0N3rd** [comment]
**Probable Solution:**
I made this library https://github.com/Circu1tI0N3rd/BKSCrawler
Please try it out and give me the feedbacks

**Comment by PythonTryHard** [comment]
Sniffed around with Wireshark, issue can be replicated

**Comment by PythonTryHard** [comment]
A potential fix is available on the `csrf` branch. Verification needed before merging.

As for the module, while I appreciate the effort, I'd refrain from using it for future-proofing as there can be changes to the system in the future, and being able to quickly patch is my main concern. Therefore having to convert `BeautifulSoup` to `html2json` while can yield runtime performance is not a high priority. I will consider making the switch in the future though, thank you for the suggestion.
